name: Update .NET local tools


on:
  push:
    branches:
    - master
    paths-ignore:
    - dotnet-tools.json


jobs:
  update-tools:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Install .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.202' # SDK Version to use.         
    - name: Try run dotnet 
      run: dotnet # start dotnet once so subsequent calls to not show the "Welcome to .NET Core" message
    - name: Show installed tools
      run: dotnet tool list